#!/bin/bash
clear
echo "###################################"
echo "# Cuestionario:  60 preg          #"
echo "###################################"
echo ""
echo "¿Qué puerto por defecto utiliza un SQUID Proxy?>> 3128"
echo "Qué función de PHP puede ser explotada en un ataque LFI? >> include()"
echo "En un ataque de Server-Side Template Injection (SSTI), un atacante puede ejecutar código arbitrario en el servidor al inyectar entrada maliciosa en una PLANTILLA de servidor."
echo "Qué tipo de ataque se produce cuando un atacante utiliza un archivo remoto para incluir contenido malicioso en un sitio web? >> RFI"
echo "Cuál es el principal objetivo de un ataque XXE? >> Leer archivos y acceder a servicios internos en el server"
echo "Un ataque XXE explota las entidades externas en documentos XML para ejecutar operaciones no autorizadas, como la lectura de archivos locales o la realización de solicitudes HTTP a servicios internos."
echo "Cuál es el principal objetivo de un ataque XSS? >> Ejecutar JavaScript en navegador victima"
echo "Un ataque CSRF engaña a la víctima para que envíe solicitudes HTTP no autorizadas a un sitio web mientras la víctima mantiene una sesión activa, explotando la confianza del sitio en las COOKIES del navegador."
echo "Qué tipo de ataque XSS se ejecuta en tiempo real y no se almacena en el servidor? >> Reflejado"
echo "¿Cuál es el principal objetivo de un ataque RFI? >> Incluir y ejecutar archivos remotos en el servidor"
echo "Qué componente de GraphQL puede ser utilizado para modificar datos en un servidor GraphQL? >> Mutaciones"
echo "Qué encabezado HTTP se utiliza para permitir el acceso a recursos entre dominios en CORS? >> Access-Control-Allow-Origin"
echo "FTP >> puerto 21"
echo "En un ataque CSRF, ¿qué tipo de solicitud HTTP es más susceptible? >> GET (mas faciles de manipular y pueden ser incluidas en un enlace malicioso"
echo "Cuál es el principal objetivo de un ataque de Log Poisoning? >> Ejecutar comandos en el servidor mediante la explotación de registros maliciosos"
echo "Un ataque de Padding Oracle explota la información de errores generada por un sistema de cifrado durante el proceso de validación del RELLENO para descifrar datos cifrados sin conocer la clave de cifrado."
echo "Qué es la enumeración del sistema en términos de seguridad informática? >> Identificar info sobre el sitema objetivo para ayudar a la explotacion"
echo "Qué tipo de ataque XSS ocurre cuando el atacante explota una vulnerabilidad en la construcción del DOM por el navegador? >> DOM-BASED"
echo "Qué es un payload Stageless? >> Payload ejecuta un solo paso"
echo "SQL >> OR AND NOT"
echo "En un ataque XSS, ¿qué elemento de seguridad del navegador suele ser eludido? >> Politicas de mismo origen"
echo " Qué es la explotación de vulnerabilidades en términos de seguridad informática? >> Aprovechar fallos en el software para tomar control del sistema"
echo "Qué función de Python puede ser explotada en un ataque de deserialización Pickle (DES-Pickle)? >> pickle.loads()"
echo "En un ataque de Log Poisoning, los atacantes pueden inyectar código malicioso en los archivos de registro a través de campos manipulados como el User-Agent, lo que permite la ejecución remota de código."
echo "Qué tipo de gestor de contenido (CMS) es Magento? >> comercio electronico"
echo "ataque Type-Juggling? >> PHP"
echo "En un ataque XXE, ¿qué componente de un documento XML se explota? >> entidades externas"
echo "Shellshock >> Bash"
echo "En las Reverse Shell, la conexión se realiza desde la máquina víctima hacia el atacante, mientras que en las Bind Shells, la conexión se realiza desde la máquina del atacante hacia la víctima"
echo "Qué característica de GraphQL puede ser explotada para obtener información sobre la estructura de un esquema GraphQL? >> Mutaciones"
echo "Cuál es el principal objetivo de un ataque LFI? >> Ejecutar JavaScript en el navegador victima"
echo "Obsidian? >> Tomar apuntes"
echo "Qué protocolo se explota en un ataque de transferencia de zona (AXFR – Full Zone Transfer)? >> DNS"
echo "Qué tipo de ataque XSS ocurre cuando el atacante explota una vulnerabilidad en el almacenamiento de datos en el servidor? >> Persistente"
echo "Qué lenguaje de plantillas es vulnerable a la inyección de plantillas en el lado del servidor (SSTI)? >> Jinja2"
echo "Qué comando LaTeX puede ser explotado para ejecutar código arbitrario en un ataque de inyección LaTeX? >> /input"
echo "Cuál es el principal objetivo de un ataque de inyección SQL? >> Obtener información confidencial almacenada en una base de datos"
echo "Qué es una inyección SQL basada en tiempo (a ciegas)? >> Una técnica de inyección SQL que se basa en la introducción de retrasos en las consultas aplicadas para extraer información sensible"
echo "Cuál es el principal objetivo de un ataque SSRF? >> Realizar solicitudes desde el servidor a sistemas internos o externos"
echo "En un ataque RFI, ¿qué protocolo suele ser utilizado para incluir archivos remotos? >> HTTP"
echo "Qué componente criptográfico se explota en un ataque de oráculo de relleno (Padding Oracle)? >> Validación de relleno en el descifrado simétrico"
echo "Qué medida de seguridad puede ayudar a prevenir ataques de condiciones de carrera? >> Implementar bloqueos y mecanismos de sincronizacion"
echo "config principal WordPress? >> wp-config.php"
echo "En qué lenguaje de programación es común el ataque de Prototype Pollution? >> JavaScript"
echo "Qué biblioteca JavaScript es vulnerable a la inyección de plantillas en el lado del cliente (CSTI)? >> Angular"
echo "Cuál es el principal objetivo de un ataque CSRF? >> Hacer que un usuario autenticado realice acciones no deseadas en una aplicación web"
echo "Cuál de los siguientes es un vector común para ataques de Log Poisoning? >> Encabezados HTTP Maliciosos"
echo "Qué protocolo de red utiliza el servicio SSH? >> TCP"
echo "Cuál es el nombre del protocolo de red utilizado por el servicio SMB? >> Server Message Block"
echo "HTTP para enviar datos formulario >> POST"



